version: '3.1'

volumes:
  config: { external: true }
  images: { external: true }

services:
  pixiecore:
    build: ./pixiecore
    ports: ["67:67", "69:69", "4011:4011"]
    network_mode: "host"

  server:
    build: ./server
    ports: ["1234:1234"]
    network_mode: "host"
    volumes:
    - config:/config
    - images:/images

  client:
    build: ./client
    ports: ["3000:3000"]
