version: '3.1'

volumes:
  config: { external: true }
  images: { external: true }

networks:
  internal: {}

services:
  pixiecore:
    build: ./pixiecore
    ports: ["67:67", "69:69", "4011:4011"]
    networks:
    - internal

  server:
    build: ./server
    ports: ["1234:1234"]
    volumes:
    - config:/config
    - images:/images
    networks:
    - internal

  client:
    build: ./client
    ports: ["3000:3000"]
